---
title: "Ibrahim Alayo"
author: "Ibrahim Alayo"
date: "`r Sys.Date()`"
---

```{r}
library(tidyverse)
```

```{r}
library(pROC)
```

```{r}
library(ggplot2)
```

```{r message= FALSE, warning=FALSE}
ndhsrasheeddata <- read_csv("ndhsrasheed.csv") %>% view()
```

```{r}
ndhsrasheedselect<-select(ndhsrasheeddata, wealth, edu, rworking, resid, relig, visithosp, teenmom, agefbirth, hofistula, tchild)
```

```{r}
ndhsrasheedselect<-drop_na(ndhsrasheedselect) %>% view()
```

```{r}
# Factor the columns for logistic regression  
ndhsrasheedselect$wealth <- as.factor(ndhsrasheedselect$wealth) 
ndhsrasheedselect$edu <- as.factor(ndhsrasheedselect$edu)  
ndhsrasheedselect$rworking <- as.factor(ndhsrasheedselect$rworking) 
ndhsrasheedselect$resid <- as.factor(ndhsrasheedselect$resid)
ndhsrasheedselect$relig <- as.factor(ndhsrasheedselect$relig) 
ndhsrasheedselect$visithosp <- as.factor(ndhsrasheedselect$visithosp) 
ndhsrasheedselect$teenmom <- as.factor(ndhsrasheedselect$teenmom)
```

```{r}
fistulamodel1 <-glm(ndhsrasheedselect$hofistula~ wealth + edu + rworking + resid + relig + visithosp + teenmom + agefbirth + tchild, family=binomial(link = "logit"), data=ndhsrasheedselect)
```

```{r}
summary(fistulamodel1)
```

```{r}
fistulamodel2 <- glm(hofistula~ wealth + edu + rworking + resid + relig + visithosp + teenmom + agefbirth +
tchild, family=binomial(link = "cloglog"),data=ndhsrasheedselect)
```

```{r}
summary(fistulamodel2)
```

```{r}
fistulamodel3 <-glm(hofistula~ wealth + edu + rworking + resid + relig + visithosp + teenmom + agefbirth + tchild, family=binomial(link = "probit"),data=ndhsrasheedselect)
```

```{r}
summary(fistulamodel3)
```

```{r}
us <- predict(fistulamodel1, type = "response")
```

```{r}
roc_curve<- roc(ndhsrasheedselect$hofistula, us)
```

```{r}
auc_value <- auc(roc_curve)
```

```{r warning=FALSE}
plot(roc_curve, main="ROC curve", col="#007c80") 
text(0.5, 0.5, paste("AUC =", round(auc_value, 4)), cex=0.8)
```

```{r}
coefficients <- coef(fistulamodel1)
odds_ratios <- exp(coefficients)
conf_intervals <- exp(confint(fistulamodel1))
```

```{r}
odds_ratios_df <- data.frame(Variable = names(odds_ratios),Odds_Ratio = odds_ratios,CI_Lower = conf_intervals[, 1],
  CI_Upper = conf_intervals[, 2])
```

```{r}
print(odds_ratios_df)
```

```{r}
ggplot(odds_ratios_df, aes(x = Variable, y = Odds_Ratio)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_Lower, ymax = CI_Upper), width = 0.2) +
  coord_flip() +
  labs(title = "Odds Ratios for Fistula Model",
       x = "Predictor Variables",
       y = "Odds Ratio (log scale)") +
  scale_y_log10() +
  theme_minimal()
```
