<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="SAMMY ODEYEMI">

<title>SAMMY ODEYEMI - HEALTH ANALYTICS WITH R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-J0F89RNG9X"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-J0F89RNG9X', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">SAMMY ODEYEMI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#portfolio"> 
<span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Odeyemi Samuel O. CV.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/arduinounoboy"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sammyoddy"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:thesamuelodeyemi@gmail.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-to-health-analytics-with-r" id="toc-introduction-to-health-analytics-with-r" class="nav-link active" data-scroll-target="#introduction-to-health-analytics-with-r">INTRODUCTION TO HEALTH ANALYTICS WITH R ⚕️</a></li>
  <li><a href="#install-necessary-packages" id="toc-install-necessary-packages" class="nav-link" data-scroll-target="#install-necessary-packages"><span style="color:#004046;">INSTALL NECESSARY PACKAGES</span> 📦</a></li>
  <li><a href="#load-libraries" id="toc-load-libraries" class="nav-link" data-scroll-target="#load-libraries"><span style="color:#004046;">LOAD LIBRARIES</span></a></li>
  <li><a href="#check-working-directory" id="toc-check-working-directory" class="nav-link" data-scroll-target="#check-working-directory"><span style="color:#004046;">CHECK WORKING DIRECTORY</span></a></li>
  <li><a href="#set-working-directory" id="toc-set-working-directory" class="nav-link" data-scroll-target="#set-working-directory"><span style="color:#004046;">SET WORKING DIRECTORY</span></a></li>
  <li><a href="#import-health-dataset-and-view" id="toc-import-health-dataset-and-view" class="nav-link" data-scroll-target="#import-health-dataset-and-view"><span style="COLOR:#004046;">IMPORT HEALTH DATASET AND VIEW</span></a></li>
  <li><a href="#display-structure-of-dataframe" id="toc-display-structure-of-dataframe" class="nav-link" data-scroll-target="#display-structure-of-dataframe">DISPLAY STRUCTURE OF DATAFRAME</a></li>
  <li><a href="#report" id="toc-report" class="nav-link" data-scroll-target="#report"><span style="COLOR:#004046;">REPORT</span></a></li>
  <li><a href="#descriptive-summary" id="toc-descriptive-summary" class="nav-link" data-scroll-target="#descriptive-summary"><span style="COLOR:#004046;">DESCRIPTIVE SUMMARY</span></a></li>
  <li><a href="#assumption-test-on-predictor-variables-to-determine-independence-using-correlation-coefficients" id="toc-assumption-test-on-predictor-variables-to-determine-independence-using-correlation-coefficients" class="nav-link" data-scroll-target="#assumption-test-on-predictor-variables-to-determine-independence-using-correlation-coefficients"><span style="COLOR:#004046;">ASSUMPTION TEST ON PREDICTOR VARIABLES TO DETERMINE INDEPENDENCE USING CORRELATION COEFFICIENTS</span></a></li>
  <li><a href="#linear-regression-models-for-predictor-variables" id="toc-linear-regression-models-for-predictor-variables" class="nav-link" data-scroll-target="#linear-regression-models-for-predictor-variables"><span style="COLOR:#004046;">LINEAR REGRESSION MODELS FOR PREDICTOR VARIABLES</span></a></li>
  <li><a href="#residuals-and-fitted-values-for-linear-model-1" id="toc-residuals-and-fitted-values-for-linear-model-1" class="nav-link" data-scroll-target="#residuals-and-fitted-values-for-linear-model-1">RESIDUALS AND FITTED VALUES FOR LINEAR MODEL 1</a>
  <ul class="collapse">
  <li><a href="#q-q-plot-of-residuals" id="toc-q-q-plot-of-residuals" class="nav-link" data-scroll-target="#q-q-plot-of-residuals">Q-Q Plot of Residuals</a></li>
  </ul></li>
  <li><a href="#overall-conclusion" id="toc-overall-conclusion" class="nav-link" data-scroll-target="#overall-conclusion">OVERALL CONCLUSION</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HEALTH ANALYTICS WITH R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>SAMMY ODEYEMI </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="HEALTH PREDICTION.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="380"></p>
</figure>
</div>
<section id="introduction-to-health-analytics-with-r" class="level2" style="color:#004046;">
<h2 style="color:#004046;" class="anchored" data-anchor-id="introduction-to-health-analytics-with-r">INTRODUCTION TO HEALTH ANALYTICS WITH R ⚕️</h2>
<div>
<p><span style="color:#282c30;"><strong>Health Analytics</strong> is a rapidly growing field that leverages data analysis to improve healthcare outcomes, optimize operations, and inform policy decisions. By analyzing health-related data, we can uncover patterns, trends, and insights that can lead to better patient care, cost management, and overall health system efficiency.</span></p>
<p><span style="color:#282c30;">In this project, I use R, a powerful statistical programming language, to analyze a <a href="https://drive.google.com/file/d/1gDY_-7nL5KUzLtmSJgI8w0LCiVkFTlDD/view?usp=drive_link" style="color:blue;">dataset</a> containing various health-related variables. The dataset includes information on individuals’ age, sex, body mass index (BMI), number of children, smoking status, region of residence, and insurance charges. The goal is to explore how these factors influence health insurance costs and identify key drivers of these costs.</span></p>
</div>
</section>
<section id="install-necessary-packages" class="level2">
<h2 class="anchored" data-anchor-id="install-necessary-packages"><span style="color:#004046;">INSTALL NECESSARY PACKAGES</span> 📦</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"corrplot"</span>,<span class="st">"ggplot2"</span>,<span class="st">"tidyr"</span>,<span class="st">"dplyr"</span>,<span class="st">"readr"</span>,<span class="st">"knitr"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <strong><code>install.packages</code></strong> function in R is used to install one or more packages from CRAN (the Comprehensive R Archive Network). The codeblock instruction is to install five packages: <strong><code>corrplot</code></strong>, <strong><code>ggplot2</code></strong>, <strong><code>tidyr</code></strong>, <strong><code>dplyr</code></strong>, and <strong><code>readr</code></strong>. Here’s a brief description of each:</p>
<ol type="1">
<li><p><strong><code>corrplot</code></strong>: This package is used for visualizing correlation matrices. It provides a variety of methods to display correlations, making it easier to understand the relationships between variables in your dataset.</p></li>
<li><p><strong><code>ggplot2</code></strong>: A powerful and widely-used package for data visualization. It implements the grammar of graphics, allowing you to create complex and aesthetically pleasing plots with a high degree of customization.</p></li>
<li><p><strong><code>tidyr</code></strong>: This package helps in tidying your data. It provides functions to reshape and clean your data, making it easier to work with and analyze. Key functions include <strong><code>gather</code></strong>, <strong><code>spread</code></strong>, <strong><code>separate</code></strong>, and <strong><code>unite</code></strong>.</p></li>
<li><p><strong><code>dplyr</code></strong>: A package for data manipulation. It provides a set of functions (verbs) that help you perform common data manipulation tasks such as filtering, selecting, mutating, summarizing, and arranging data. It’s known for its simplicity and speed.</p></li>
<li><p><strong><code>readr</code></strong>: This package is used for reading rectangular data (like CSV files) into R. It provides functions that are faster and more convenient than the base R functions for reading data.</p></li>
<li><p><strong><code>knitr</code></strong>: This package is used for dynamic report generation in R. It allows to integrate R code with LaTeX, HTML, Markdown, and other formats, making it easier to create reproducible reports and documents that include both code and output.</p></li>
</ol>
</section>
<section id="load-libraries" class="level2">
<h2 class="anchored" data-anchor-id="load-libraries"><span style="color:#004046;">LOAD LIBRARIES</span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr) </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.2     ✔ tibble    3.2.0
✔ purrr     1.0.1     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By calling these packages, one is equipped with powerful tools to clean, manipulate, visualize, and analyze the health dataset effectively.</p>
</section>
<section id="check-working-directory" class="level2">
<h2 class="anchored" data-anchor-id="check-working-directory"><span style="color:#004046;">CHECK WORKING DIRECTORY</span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/SAMMY/Desktop/Portfoliooo/Sammy Odeyemi/R Projects/Health Analysis"</code></pre>
</div>
</div>
<p>The&nbsp;<code>getwd()</code>&nbsp;function in R stands for “get working directory.” It returns the current working directory of the R session. The working directory is the folder where R reads and saves files by default. Knowing the current working directory is important because it helps to understand where your files are being stored and accessed from.</p>
</section>
<section id="set-working-directory" class="level2">
<h2 class="anchored" data-anchor-id="set-working-directory"><span style="color:#004046;">SET WORKING DIRECTORY</span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/SAMMY/Desktop/Portfoliooo/Sammy Odeyemi/R Projects/Health Analysis"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The&nbsp;<code>setwd()</code>&nbsp;function in R sets the working directory to a specified path. This means R will read and write files from this directory by default.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>As in your Desktop/Workspace, the Working Directory would be different!</p>
</div>
</div>
</section>
<section id="import-health-dataset-and-view" class="level2">
<h2 class="anchored" data-anchor-id="import-health-dataset-and-view"><span style="COLOR:#004046;">IMPORT HEALTH DATASET AND VIEW</span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>healthdata<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"Health-Insurance-Dataset.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1338 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): sex, smoker, region
dbl (4): age, bmi, children, charges

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(healthdata,<span class="dv">20</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">age</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">bmi</th>
<th style="text-align: right;">children</th>
<th style="text-align: left;">smoker</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">charges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">27.900</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">southwest</td>
<td style="text-align: right;">16884.924</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">33.770</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">southeast</td>
<td style="text-align: right;">1725.552</td>
</tr>
<tr class="odd">
<td style="text-align: right;">28</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">33.000</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">southeast</td>
<td style="text-align: right;">4449.462</td>
</tr>
<tr class="even">
<td style="text-align: right;">33</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">22.705</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">northwest</td>
<td style="text-align: right;">21984.471</td>
</tr>
<tr class="odd">
<td style="text-align: right;">32</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">28.880</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">northwest</td>
<td style="text-align: right;">3866.855</td>
</tr>
<tr class="even">
<td style="text-align: right;">31</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">25.740</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">southeast</td>
<td style="text-align: right;">3756.622</td>
</tr>
<tr class="odd">
<td style="text-align: right;">46</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">33.440</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">southeast</td>
<td style="text-align: right;">8240.590</td>
</tr>
<tr class="even">
<td style="text-align: right;">37</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">27.740</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">northwest</td>
<td style="text-align: right;">7281.506</td>
</tr>
<tr class="odd">
<td style="text-align: right;">37</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">29.830</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">northeast</td>
<td style="text-align: right;">6406.411</td>
</tr>
<tr class="even">
<td style="text-align: right;">60</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">25.840</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">northwest</td>
<td style="text-align: right;">28923.137</td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">26.220</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">northeast</td>
<td style="text-align: right;">2721.321</td>
</tr>
<tr class="even">
<td style="text-align: right;">62</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">26.290</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">southeast</td>
<td style="text-align: right;">27808.725</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">34.400</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">southwest</td>
<td style="text-align: right;">1826.843</td>
</tr>
<tr class="even">
<td style="text-align: right;">56</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">39.820</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">southeast</td>
<td style="text-align: right;">11090.718</td>
</tr>
<tr class="odd">
<td style="text-align: right;">27</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">42.130</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">southeast</td>
<td style="text-align: right;">39611.758</td>
</tr>
<tr class="even">
<td style="text-align: right;">19</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">24.600</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">southwest</td>
<td style="text-align: right;">1837.237</td>
</tr>
<tr class="odd">
<td style="text-align: right;">52</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">30.780</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">northeast</td>
<td style="text-align: right;">10797.336</td>
</tr>
<tr class="even">
<td style="text-align: right;">23</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">23.845</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">northeast</td>
<td style="text-align: right;">2395.172</td>
</tr>
<tr class="odd">
<td style="text-align: right;">56</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">40.300</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">southwest</td>
<td style="text-align: right;">10602.385</td>
</tr>
<tr class="even">
<td style="text-align: right;">30</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">35.300</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">southwest</td>
<td style="text-align: right;">36837.467</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><p><strong><code>healthdata &lt;- read_csv("Health-Insurance-Dataset.csv")</code></strong>: Reads the CSV file named “Health-Insurance-Dataset.csv” into a data frame called <strong><code>healthdata</code></strong>. This function is part of the <strong><code>readr</code></strong> package and is used to import data into R for analysis.</p></li>
<li><p><strong><code>View(healthdata)</code></strong>: Opens a spreadsheet-like view of the <strong><code>healthdata</code></strong> data frame in RStudio, allowing to inspect the data visually.</p></li>
</ul>
</section>
<section id="display-structure-of-dataframe" class="level2" style="color:#004046;">
<h2 style="color:#004046;" class="anchored" data-anchor-id="display-structure-of-dataframe">DISPLAY STRUCTURE OF DATAFRAME</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(healthdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [1,338 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ age     : num [1:1338] 19 18 28 33 32 31 46 37 37 60 ...
 $ sex     : chr [1:1338] "female" "male" "male" "male" ...
 $ bmi     : num [1:1338] 27.9 33.8 33 22.7 28.9 ...
 $ children: num [1:1338] 0 1 3 0 0 0 1 3 2 0 ...
 $ smoker  : chr [1:1338] "yes" "no" "no" "no" ...
 $ region  : chr [1:1338] "southwest" "southeast" "southeast" "northwest" ...
 $ charges : num [1:1338] 16885 1726 4449 21984 3867 ...
 - attr(*, "spec")=
  .. cols(
  ..   age = col_double(),
  ..   sex = col_character(),
  ..   bmi = col_double(),
  ..   children = col_double(),
  ..   smoker = col_character(),
  ..   region = col_character(),
  ..   charges = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<ul>
<li><p><span style="color:#0c1621;"><strong><code>str(healthdata)</code></strong>: Provides a compact, human-readable summary of the structure of the <strong><code>healthdata</code></strong> data frame, including the type of each variable and a preview of the data.</span></p>
<h2 id="visualizations" style="color:#004046;" class="anchored">VISUALIZATIONS 📊</h2></li>
</ul>
<section id="visualize-predictor-variable-age" class="level4">
<h4 class="anchored" data-anchor-id="visualize-predictor-variable-age"><span style="color:#004046;">VISUALIZE PREDICTOR VARIABLE</span> <span style="color:orange;">AGE</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(healthdata,<span class="fu">aes</span>(<span class="at">x=</span>age)) <span class="sc">+</span>   </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">"#004046"</span>,<span class="at">binwidth =</span> <span class="dv">5</span>,<span class="at">color=</span><span class="st">"bisque"</span>) <span class="sc">+</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Visualization for Predictor Variable Age"</span>) <span class="sc">+</span>  </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span style="color:#0c1621;">This block of code creates a histogram to visualize the distribution of the <strong><code>age</code></strong> variable in the <strong><code>healthdata</code></strong> data frame. The histogram uses bins of 5 years to group the ages, and it is styled with specific fill and border colors. The plot is titled “Visualization for Predictor Variable Age” and uses a minimal theme for a clean look.</span></p>
<p><span style="color:#0c1621;">This visualization helps in understanding the distribution of ages in the dataset, which can be useful for identifying patterns or anomalies in the data.</span></p>
</section>
<section id="visualize-predictor-variable-sex" class="level4">
<h4 class="anchored" data-anchor-id="visualize-predictor-variable-sex"><span style="color:#004046;">VISUALIZE PREDICTOR VARIABLE</span> <span style="COLOR:#CBC3E3;"><strong>SEX</strong></span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(healthdata,<span class="fu">aes</span>(<span class="at">x=</span>sex, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color=</span><span class="st">"bisque"</span>) <span class="sc">+</span>   </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"male"</span><span class="ot">=</span><span class="st">"#004046"</span>,<span class="st">"female"</span><span class="ot">=</span><span class="st">"#007d76"</span>)) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">stat =</span> <span class="st">"count"</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Visualization for Predictor Variable Sex"</span>) <span class="sc">+</span>   </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span style="color:#0c1621;">This block of code creates a bar plot to visualize the distribution of the <strong><code>sex</code></strong> variable in the <strong><code>healthdata</code></strong> dataset. The bars are colored based on sex, with custom colors for “male” and “female.” The plot includes count labels above each bar, a title “Visualization for Predictor Variable Sex,” and uses a minimal theme for a clean look.</span></p>
<p><span style="color:#0c1621;">This visualization helps in understanding the distribution of sexes in the dataset, which can be useful for identifying patterns or anomalies in the data.</span></p>
</section>
<section id="visualize-predictor-variable-bmi" class="level4">
<h4 class="anchored" data-anchor-id="visualize-predictor-variable-bmi"><span style="COLOR:#004046;"><strong>VISUALIZE PREDICTOR VARIABLE</strong></span> <span style="color:orange;"><strong>BMI</strong></span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(healthdata, <span class="fu">aes</span>(<span class="at">x =</span> bmi)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">fill =</span> <span class="st">"#004046"</span>, <span class="at">color =</span> <span class="st">"bisque"</span>) <span class="sc">+</span>   </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"BMI Distribution"</span>, <span class="at">x =</span> <span class="st">"BMI"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span>   </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span style="color:#0c1621;">This block of code creates a histogram to visualize the distribution of the <strong><code>bmi</code></strong> variable in the <strong><code>healthdata</code></strong> dataset. The histogram uses bins of 2 units to group the BMI values and is styled with a specific fill color and border color. The plot is titled “BMI Distribution” and uses a minimal theme for a clean look.</span></p>
<p><span style="color:#0c1621;">This visualization helps in understanding the distribution of BMI values in the dataset, which can be useful for identifying patterns or anomalies in the data.</span></p>
</section>
<section id="visualize-predictor-variable-children" class="level4">
<h4 class="anchored" data-anchor-id="visualize-predictor-variable-children"><span style="COLOR: #004046;">VISUALIZE PREDICTOR VARIABLE</span> <span style="COLOR:#CBC3E3;">CHILDREN</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(healthdata, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(children))) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#004046"</span>, <span class="at">color=</span><span class="st">"bisque"</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Children"</span>, <span class="at">x =</span> <span class="st">"Children"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">stat =</span> <span class="st">"count"</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span style="color:#0c1621;">This block of code creates a bar plot to visualize the distribution of the <strong><code>children</code></strong> variable in the <strong><code>healthdata</code></strong> dataset. The bars are colored with a specific fill and border color. The plot includes count labels above each bar, a title “Number of Children,” and uses a minimal theme for a clean look.</span></p>
<p><span style="color:#0c1621;">This visualization helps in understanding the distribution of the number of children in the dataset, which can be useful for identifying patterns or anomalies in the data.</span></p>
</section>
<section id="visualize-predictor-variable-smoker" class="level4">
<h4 class="anchored" data-anchor-id="visualize-predictor-variable-smoker"><span style="color:#CBC3E3;">VISUALIZE PREDICTOR VARIABLE</span> <span style="color:orange;">SMOKER</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(healthdata, <span class="fu">aes</span>(<span class="at">x =</span> smoker, <span class="at">fill =</span> smoker)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_bar</span>() <span class="sc">+</span>   </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Smoker vs. Non-Smoker"</span>, <span class="at">x =</span> <span class="st">"Smoker"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span>       <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"yes"</span> <span class="ot">=</span> <span class="st">"antiquewhite4"</span>, <span class="st">"no"</span> <span class="ot">=</span> <span class="st">"#004046"</span>)) <span class="sc">+</span>     <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span style="color:#0c1621;">This block of code creates a bar plot to visualize the distribution of the <strong><code>smoker</code></strong> variable in the <strong><code>healthdata</code></strong> dataset. The bars are colored based on smoking status, with custom colors for “yes” and “no.” The plot includes count labels above each bar, a title “Smoker vs.&nbsp;Non-Smoker,” and uses a minimal theme for a clean look.</span></p>
<p><span style="color:#0c1621;">This visualization helps in understanding the distribution of smokers and non-smokers in the dataset, which can be useful for identifying patterns or anomalies in the data.</span></p>
</section>
<section id="visualize-predictor-variable-region" class="level4">
<h4 class="anchored" data-anchor-id="visualize-predictor-variable-region"><span style="color:#004046;">VISUALIZE PREDICTOR VARIABLE</span> <span style="color:#CBC3E3;">REGION</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(healthdata, <span class="fu">aes</span>(<span class="at">x =</span> region, <span class="at">fill =</span> region)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution by Region"</span>, <span class="at">x =</span> <span class="st">"Region"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span>   <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"southwest"</span> <span class="ot">=</span> <span class="st">"darkorchid"</span>, <span class="st">"southeast"</span> <span class="ot">=</span> <span class="st">"#004046"</span>, <span class="st">"northwest"</span> <span class="ot">=</span> <span class="st">"antiquewhite4"</span>, <span class="st">"northeast"</span> <span class="ot">=</span> <span class="st">"darkgoldenrod"</span>)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span style="color:#0c1621;">This block of code creates a bar plot to visualize the distribution of the <strong><code>region</code></strong> variable in the <strong><code>healthdata</code></strong> dataset. The bars are colored based on the region, with custom colors for “southwest,” “southeast,” “northwest,” and “northeast.” The plot includes count labels above each bar, a title “Distribution by Region,” and uses a minimal theme for a clean look.</span></p>
<p><span style="color:#0c1621;">This visualization helps in understanding the distribution of regions in the dataset, which can be useful for identifying patterns or anomalies in the data.</span></p>
</section>
<section id="visualize-predictor-variable-charges" class="level4">
<h4 class="anchored" data-anchor-id="visualize-predictor-variable-charges"><span style="color:#004046;">VISUALIZE PREDICTOR VARIABLE</span> <span style="color:orange;">CHARGES</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(healthdata, <span class="fu">aes</span>(<span class="at">x =</span> charges)) <span class="sc">+</span>   </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"#004046"</span>, <span class="at">alpha =</span> <span class="fl">0.9</span>, <span class="at">color=</span><span class="st">"bisque"</span>) <span class="sc">+</span>   </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density of Charges"</span>, <span class="at">x =</span> <span class="st">"Charges"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span>   <span class="fu">theme_minimal</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span style="color:#0c1621;">This block of code creates a density plot to visualize the distribution of the <strong><code>charges</code></strong> variable in the <strong><code>healthdata</code></strong> dataset. The density plot is styled with a specific fill color, transparency level, and border color. The plot is titled “Density of Charges” and uses a minimal theme for a clean look.</span></p>
<p><span style="color:#0c1621;">This visualization helps in understanding the distribution of charges in the dataset, which can be useful for identifying patterns or anomalies in the data.</span></p>
</section>
</section>
<section id="report" class="level2">
<h2 class="anchored" data-anchor-id="report"><span style="COLOR:#004046;">REPORT</span></h2>
<p>Piecing it altogether, we make a report off of the charts generated in RStudio using the viz Tool: Power BI</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="HEALTHDATA REPORT.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</section>
<section id="descriptive-summary" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-summary"><span style="COLOR:#004046;">DESCRIPTIVE SUMMARY</span></h2>
<p>The&nbsp;<code>summary()</code>&nbsp;function in R provides a quick overview of the dataset, including basic statistics for each variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(healthdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            sex                 bmi           children    
 Min.   :18.00   Length:1338        Min.   :15.96   Min.   :0.000  
 1st Qu.:27.00   Class :character   1st Qu.:26.30   1st Qu.:0.000  
 Median :39.00   Mode  :character   Median :30.40   Median :1.000  
 Mean   :39.21                      Mean   :30.66   Mean   :1.095  
 3rd Qu.:51.00                      3rd Qu.:34.69   3rd Qu.:2.000  
 Max.   :64.00                      Max.   :53.13   Max.   :5.000  
    smoker             region             charges     
 Length:1338        Length:1338        Min.   : 1122  
 Class :character   Class :character   1st Qu.: 4740  
 Mode  :character   Mode  :character   Median : 9382  
                                       Mean   :13270  
                                       3rd Qu.:16640  
                                       Max.   :63770  </code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation of Descriptive Statistics
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Age</strong>: The ages in your dataset range from <strong>18</strong> to <strong>64</strong> years, with a median age of <strong>39</strong>. This indicates a fairly balanced distribution of ages around the middle age group.</p></li>
<li><p><strong>BMI</strong>: BMI values range from <strong>15.96</strong> to <strong>53.13</strong>, with a median of <strong>30.40</strong>. The mean BMI is slightly higher at <strong>30.66</strong>, suggesting a slight skew towards higher BMI values.</p></li>
<li><p><strong>Children</strong>: The number of children ranges from <strong>0</strong> to <strong>5</strong>, with a median of <strong>1</strong>. This shows that most individuals have one or no children.</p></li>
<li><p><strong>Charges</strong>: Medical charges vary widely from <strong>$1,122</strong> to <strong>$63,770</strong>, with a median charge of <strong>$9,382</strong>. The mean charge is <strong>$13,270</strong>, indicating a right-skewed distribution with some high-cost outliers.</p></li>
<li><p><strong>Sex, Smoker, Region</strong>: These are categorical variables, and their summary indicates the dataset includes diverse categories for each.</p></li>
</ul>
</div>
</div>
</section>
<section id="assumption-test-on-predictor-variables-to-determine-independence-using-correlation-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="assumption-test-on-predictor-variables-to-determine-independence-using-correlation-coefficients"><span style="COLOR:#004046;">ASSUMPTION TEST ON PREDICTOR VARIABLES TO DETERMINE INDEPENDENCE USING CORRELATION COEFFICIENTS</span></h2>
<p>It becomes imperative to convert non-numeric columns in the <code>healthdata</code> dataset to numeric values and this is essential for performing further numerical analyses and visualizations</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert to numeric and factors, the columns that are non-numeric </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>healthdata<span class="sc">$</span>sex<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(healthdata<span class="sc">$</span>sex))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>healthdata<span class="sc">$</span>smoker<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(healthdata<span class="sc">$</span>smoker))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>healthdata<span class="sc">$</span>region<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(healthdata<span class="sc">$</span>region))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#USING SCATTERPLOTS AND CORRELATION MATRIX </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>corr_matrix<span class="ot">&lt;-</span> <span class="fu">cor</span>(healthdata[,<span class="fu">c</span>(<span class="st">"age"</span>,<span class="st">"sex"</span>,<span class="st">"bmi"</span>,<span class="st">"children"</span>,<span class="st">"smoker"</span>,<span class="st">"region"</span>,<span class="st">"charges"</span>)])</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>corr_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  age          sex         bmi   children       smoker
age       1.000000000 -0.020855872 0.109271882 0.04246900 -0.025018752
sex      -0.020855872  1.000000000 0.046371151 0.01716298  0.076184817
bmi       0.109271882  0.046371151 1.000000000 0.01275890  0.003750426
children  0.042468999  0.017162978 0.012758901 1.00000000  0.007673120
smoker   -0.025018752  0.076184817 0.003750426 0.00767312  1.000000000
region    0.002127313  0.004588385 0.157565849 0.01656945 -0.002180682
charges   0.299008193  0.057292062 0.198340969 0.06799823  0.787251430
               region      charges
age       0.002127313  0.299008193
sex       0.004588385  0.057292062
bmi       0.157565849  0.198340969
children  0.016569446  0.067998227
smoker   -0.002180682  0.787251430
region    1.000000000 -0.006208235
charges  -0.006208235  1.000000000</code></pre>
</div>
</div>
<p>In this block of code, we calculate the correlation matrix for selected variables in the <strong><code>healthdata</code></strong> dataset. This matrix helps in understanding the linear relationships between pairs of variables such as <code>age</code>,&nbsp;<code>sex</code>,&nbsp;<code>bmi</code>,&nbsp;<code>children</code>,&nbsp;<code>smoker</code>,&nbsp;<code>region</code>, and&nbsp;<code>charges</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Visualizing for correlation </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>corr_colors <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"#E0F2F1"</span>, <span class="st">"#007D76"</span>))(<span class="dv">100</span>) </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(corr_matrix,<span class="at">method=</span><span class="st">"color"</span>,<span class="at">addCoef.col =</span> <span class="st">"black"</span>,<span class="at">col=</span>corr_colors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Above is a color-coded plot that clearly shows the strength and direction of relationships between the variables, aiding in the identification of patterns and potential multicollinearity.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation of Correlation Matrix
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Age</strong>: Positively correlated with <strong><code>charges</code></strong> (0.299).</p></li>
<li><p><strong>Sex</strong>: Weak correlations with all variables.</p></li>
<li><p><strong>BMI</strong>: Positively correlated with <strong><code>charges</code></strong> (0.198) and <strong><code>region</code></strong> (0.158).</p></li>
<li><p><strong>Children</strong>: Weak correlations with all variables.</p></li>
<li><p><strong>Smoker</strong>: Strongly correlated with <strong><code>charges</code></strong> (0.787).</p></li>
<li><p><strong>Region</strong>: Weak correlations with all variables.</p></li>
<li><p><strong>Charges</strong>: Strongly correlated with <strong><code>smoker</code></strong> (0.787), moderately with <strong><code>age</code></strong> (0.299) and <strong><code>BMI</code></strong> (0.198).</p></li>
</ul>
<p>Key relationships: <strong><code>smoker</code></strong> and <strong><code>charges</code></strong> (strong), <strong><code>age</code></strong> and <strong><code>charges</code></strong> (moderate), <strong><code>BMI</code></strong> and <strong><code>charges</code></strong> (moderate). Other variables show weak correlations.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(<span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> smoker <span class="sc">+</span> region <span class="sc">+</span> charges, <span class="at">data =</span> healthdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above chart and block of code helps in visualizing a pairwise relationship between the variables.</p>
<p>A scatterplot matrix is visualized, where each cell in the matrix is a scatterplot of one variable against another.</p>
</section>
<section id="linear-regression-models-for-predictor-variables" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-models-for-predictor-variables"><span style="COLOR:#004046;">LINEAR REGRESSION MODELS FOR PREDICTOR VARIABLES</span></h2>
<section id="linear-model-1" class="level4">
<h4 class="anchored" data-anchor-id="linear-model-1"><span style="color:#004046">LINEAR MODEL 1</span></h4>
<p>The codeblock below fits a linear regression model to predict&nbsp;<code>charges</code>&nbsp;based on&nbsp;<code>smoker</code>,&nbsp;<code>age</code> and&nbsp;<code>bmi</code></p>
<p><strong>Description</strong>:</p>
<ul>
<li><p><strong>Model</strong>: Predicts <strong><code>charges</code></strong> using <strong><code>smoker</code></strong>, <strong><code>age</code></strong>, and <strong><code>bmi</code></strong>.</p></li>
<li><p><strong>Summary</strong>: Provides coefficients, significance, R-squared, and residuals.</p></li>
</ul>
<p>This helps understand how these predictors influence <strong><code>charges</code></strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic regression models for predictor variables </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Age, Smoker and BMI  </span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>lm1<span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> smoker <span class="sc">+</span> age <span class="sc">+</span> bmi, healthdata) </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker + age + bmi, data = healthdata)

Residuals:
     Min       1Q   Median       3Q      Max 
-12415.4  -2970.9   -980.5   1480.0  28971.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -35500.51    1060.50  -33.48   &lt;2e-16 ***
smoker       23823.68     412.87   57.70   &lt;2e-16 ***
age            259.55      11.93   21.75   &lt;2e-16 ***
bmi            322.62      27.49   11.74   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6092 on 1334 degrees of freedom
Multiple R-squared:  0.7475,    Adjusted R-squared:  0.7469 
F-statistic:  1316 on 3 and 1334 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation of Linear Model 1
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Coefficients</strong>:</p>
<ul>
<li><p><strong>Intercept</strong>: -35500.51</p></li>
<li><p><strong>Smoker</strong>: +23823.68 (higher charges for smokers)</p></li>
<li><p><strong>Age</strong>: +259.55 (increase per year)</p></li>
<li><p><strong>BMI</strong>: +322.62 (increase per unit)</p></li>
</ul>
<p><strong>Significance</strong>: All predictors are highly significant (p &lt; 2e-16).</p>
<p><strong>Model Fit</strong>:</p>
<ul>
<li><p><strong>R-squared</strong>: 0.7475 (74.75% variability explained)</p></li>
<li><p><strong>Residual Standard Error</strong>: 6092</p></li>
</ul>
<p><strong>Conclusion</strong>: Smoking, age, and BMI significantly impact charges, with smoking having the largest effect.</p>
</div>
</div>
</section>
<section id="linear-model-2" class="level4" style="color:#004046">
<h4 style="color:#004046" class="anchored" data-anchor-id="linear-model-2">LINEAR MODEL 2</h4>
<p>The codeblock below fits a linear regression model to predict&nbsp;<code>charges</code>&nbsp;based on&nbsp;<code>smoker</code>,&nbsp;<code>age</code>,&nbsp;<code>bmi</code>,&nbsp;<code>children</code>,&nbsp;<code>region</code>, and&nbsp;<code>sex</code></p>
<p><strong>Description</strong>:</p>
<ul>
<li><p><strong>Model</strong>: Predicts <strong><code>charges</code></strong> using <strong><code>smoker</code></strong>, <strong><code>age</code></strong>, <strong><code>bmi</code></strong>, <strong><code>children</code></strong>, <strong><code>region</code></strong>, and <strong><code>sex</code></strong>.</p></li>
<li><p><strong>Summary</strong>: Provides coefficients, significance, R-squared, and residuals.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Logistic regression models for predictor variables </span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Age, Smoker, children, region, sex and BMI   </span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  lm2<span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> smoker <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> region <span class="sc">+</span> sex, healthdata) </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker + age + bmi + children + region + 
    sex, data = healthdata)

Residuals:
   Min     1Q Median     3Q    Max 
-11343  -2807  -1017   1408  29752 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -35151.14    1174.41 -29.931  &lt; 2e-16 ***
smoker       23820.43     411.84  57.839  &lt; 2e-16 ***
age            257.29      11.89  21.647  &lt; 2e-16 ***
bmi            332.57      27.72  11.997  &lt; 2e-16 ***
children       479.37     137.64   3.483 0.000513 ***
region        -353.64     151.93  -2.328 0.020077 *  
sex           -131.11     332.81  -0.394 0.693681    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6060 on 1331 degrees of freedom
Multiple R-squared:  0.7507,    Adjusted R-squared:  0.7496 
F-statistic: 668.1 on 6 and 1331 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled" style="color:0c1621;">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation of Linear Model 2
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Coefficients</strong>:</p>
<ul>
<li><p><strong>Smoker</strong>: +23820.43 (higher charges)</p></li>
<li><p><strong>Age</strong>: +257.29 (per year)</p></li>
<li><p><strong>BMI</strong>: +332.57 (per unit)</p></li>
<li><p><strong>Children</strong>: +479.37 (per child)</p></li>
<li><p><strong>Region</strong>: -353.64 (slight decrease)</p></li>
<li><p><strong>Sex</strong>: -131.11 (not significant)</p></li>
</ul>
<p><strong>Significance</strong>: All predictors except <strong><code>sex</code></strong> are significant.</p>
<p><strong>Model Fit</strong>:</p>
<ul>
<li><p><strong>R-squared</strong>: 0.7507 (75.07% variability explained)</p></li>
<li><p><strong>Residual Standard Error</strong>: 6060</p></li>
</ul>
<p><strong>Conclusion</strong>: Smoking, age, BMI, children, and region significantly impact charges, with smoking having the largest effect.</p>
</div>
</div>
</section>
<section id="linear-model-3" class="level4" style="color:#004046;">
<h4 style="color:#004046;" class="anchored" data-anchor-id="linear-model-3">LINEAR MODEL 3</h4>
<p><span style="color:0c1621;">The codeblock below fits a linear regression model to predict&nbsp;<code>charges</code>&nbsp;based on&nbsp;<code>smoker</code>,&nbsp;<code>age</code>,&nbsp;<code>bmi</code>,&nbsp;<code>children</code> and&nbsp;<code>region</code></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic regression models for predictor variables </span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Age, Smoker, children, region, BMI   </span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>lm3<span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> smoker <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> region, healthdata) </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker + age + bmi + children + region, 
    data = healthdata)

Residuals:
   Min     1Q Median     3Q    Max 
-11404  -2805   -992   1400  29694 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -35321.62    1091.42 -32.363  &lt; 2e-16 ***
smoker       23808.21     410.54  57.992  &lt; 2e-16 ***
age            257.41      11.88  21.670  &lt; 2e-16 ***
bmi            332.04      27.68  11.995  &lt; 2e-16 ***
children       478.44     137.58   3.478 0.000522 ***
region        -353.45     151.88  -2.327 0.020104 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6058 on 1332 degrees of freedom
Multiple R-squared:  0.7507,    Adjusted R-squared:  0.7498 
F-statistic: 802.2 on 5 and 1332 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation of the Linear Regression Model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Coefficients</strong>:</p>
<ul>
<li><p><strong>Smoker</strong>: +23808.21 (higher charges)</p></li>
<li><p><strong>Age</strong>: +257.41 (per year)</p></li>
<li><p><strong>BMI</strong>: +332.04 (per unit)</p></li>
<li><p><strong>Children</strong>: +478.44 (per child)</p></li>
<li><p><strong>Region</strong>: -353.45 (slight decrease)</p></li>
</ul>
<p><strong>Significance</strong>:</p>
<ul>
<li>All predictors are significant (<strong><code>p &lt; 0.05</code></strong>).</li>
</ul>
<p><strong>Model Fit</strong>:</p>
<ul>
<li><p><strong>R-squared</strong>: 0.7507 (75.07% variability explained)</p></li>
<li><p><strong>Residual Standard Error</strong>: 6058</p></li>
</ul>
<p><strong>Conclusion</strong>:</p>
<ul>
<li>Smoking, age, BMI, children, and region significantly impact charges, with smoking having the largest effect.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="residuals-and-fitted-values-for-linear-model-1" class="level2" style="color:#004046;">
<h2 style="color:#004046;" class="anchored" data-anchor-id="residuals-and-fitted-values-for-linear-model-1">RESIDUALS AND FITTED VALUES FOR LINEAR MODEL 1</h2>
<p>The codeblock below calculates the residuals and fitted values for the linear regression model&nbsp;<code>lm1</code>&nbsp;and stores them in a data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate residuals and fitted values for residuals</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>residualslm1<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">residuals=</span><span class="fu">resid</span>(lm1), <span class="at">Fitted=</span><span class="fu">fitted</span>(lm1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Description</strong>:</p>
<ul>
<li><p><strong>Residuals</strong>: Differences between observed and predicted values from <strong><code>lm1</code></strong>.</p>
<ul>
<li><strong><code>resid(lm1)</code></strong>: Extracts residuals from <strong><code>lm1</code></strong>.</li>
</ul></li>
<li><p><strong>Fitted Values</strong>: Predicted values from <strong><code>lm1</code></strong>.</p>
<ul>
<li><strong><code>fitted(lm1)</code></strong>: Extracts fitted values from <strong><code>lm1</code></strong>.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create Visuals for Residuals and Fitted Values  </span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(residualslm1, <span class="fu">aes</span>(Fitted,residuals))<span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span><span class="st">"#004046"</span>)) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>,<span class="at">linetype=</span><span class="st">"dashed"</span>,<span class="at">color=</span><span class="st">"#004046"</span>)<span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs Fitted Plot"</span>, <span class="at">x=</span><span class="st">"Fitted Values"</span>,<span class="at">y=</span><span class="st">"Residuals"</span>)<span class="sc">+</span>   <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation of the Residuals vs Fitted Plot
</div>
</div>
<div class="callout-body-container callout-body">
<p>The plot visualizes the residuals (differences between observed and predicted values) against the fitted values from your linear regression model.</p>
<p><strong>Key Observations</strong>:</p>
<ul>
<li><p><strong>No Clear Pattern</strong>: The residuals are scattered randomly around the horizontal dashed line at zero, indicating no obvious pattern.</p></li>
<li><p><strong>Homoscedasticity</strong>: The spread of residuals appears consistent across all fitted values, suggesting constant variance (homoscedasticity).</p></li>
<li><p><strong>Outliers</strong>: There are a few points far from the zero line, which might be outliers.</p></li>
</ul>
<p><strong>Conclusion</strong>:</p>
<ul>
<li><p>The random scatter and consistent spread suggest that the model’s assumptions are reasonably met.</p></li>
<li><p>The lack of a clear pattern indicates that the model does not suffer from major issues like non-linearity.</p></li>
</ul>
</div>
</div>
<section id="q-q-plot-of-residuals" class="level3">
<h3 class="anchored" data-anchor-id="q-q-plot-of-residuals">Q-Q Plot of Residuals</h3>
<p>The Q-Q plot compares the residuals’ quantiles to a normal distribution’s quantiles.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#QQ Plot of Residuals</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(residualslm1, <span class="fu">aes</span>(<span class="at">sample=</span>residuals))<span class="sc">+</span>   <span class="fu">stat_qq</span>(<span class="at">color=</span><span class="st">"#004046"</span>)<span class="sc">+</span>   <span class="fu">stat_qq_line</span>(<span class="at">color=</span><span class="st">"#004046"</span>)<span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Q-Q Plot of Residuals"</span>, <span class="at">x=</span><span class="st">"Theoretical Quantiles"</span>,<span class="at">y=</span><span class="st">"Sample Quantiles"</span>)<span class="sc">+</span>   <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HEALTHDATA_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Central Points</strong>: Residuals are approximately normally distributed.</p></li>
<li><p><strong>Deviations at Extremes</strong>: More extreme residuals than expected, indicating heavier tails.</p></li>
</ul>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion:</h4>
<p>The residuals deviate from normality at the extremes, suggesting potential issues with the model’s assumptions. Consider transformations or alternative models.</p>
</section>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Source file
</div>
</div>
<div class="callout-body-container callout-body">
<p>Access source file <a href="https://drive.google.com/file/d/1Hol9apORGNO0ZIK3dJv3l1Tn2t-jqaqR/view?usp=drive_link" style="color:blue;">here</a></p>
</div>
</div>
</section>
</section>
<section id="overall-conclusion" class="level2" style="color:##004046;">
<h2 style="color:##004046;" class="anchored" data-anchor-id="overall-conclusion">OVERALL CONCLUSION</h2>
<p><span style="color:0c1621;">In this health analytics project, I explored various factors affecting medical charges using a dataset that included variables such as age, BMI, number of children, smoking status, region, and charges. Here’s a summary of our key findings and analyses:</span></p>
<ol type="1">
<li><span style="color:0c1621;"><strong>Data Visualization</strong>:</span></li>
</ol>
<ul>
<li><p><span style="color:0c1621;"><code>ggplot2</code> was used to create visualizations that highlighted the relationships between different variables. For example, it was observed that smokers tend to have higher medical charges compared to non-smokers.</span></p></li>
<li><p><span style="color:0c1621;">The <code>corrplot</code> package helped to visualize correlations between variables, revealing significant relationships, such as the positive correlation between BMI and charges.</span></p></li>
</ul>
<ol start="2" type="1">
<li><span style="color:0c1621;"><strong>Data Transformation and Cleaning</strong>:</span></li>
</ol>
<ul>
<li><span style="color:0c1621;">Using <code>dplyr</code> and <code>tidyr</code>, the data was transformed to ensure it was ready for analysis. This creating new variables where necessary.</span></li>
</ul>
<ol start="3" type="1">
<li><span style="color:0c1621;"><strong>Linear Regression Modeling</strong>:</span></li>
</ol>
<ul>
<li><p><span style="color:0c1621;">Linear regression modeling was performed to predict medical charges based on various predictor variables. The models showed that age, BMI, smoking status, and region are significant predictors of medical charges.</span></p></li>
<li><p><span style="color:0c1621;">The Q-Q plot of residuals indicated that while the central residuals were approximately normally distributed, there were deviations at the extremes, suggesting potential issues with the model’s assumptions.</span></p></li>
</ul>
<ol start="4" type="1">
<li><span style="color:0c1621;"><strong>Model Evaluation</strong>:</span></li>
</ol>
<ul>
<li><span style="color:0c1621;">I evaluated the model’s performance and identified areas where it could be improved. The deviations in the Q-Q plot suggest that there might be need to consider transformations or alternative models to better fit the data.</span></li>
</ul>
<section id="final-thoughts" class="level4" style="color:#004046;">
<h4 style="color:#004046;" class="anchored" data-anchor-id="final-thoughts">FINAL THOUGHTS:</h4>
<p><span style="color:#0c1621;">This analysis provides valuable insights into the factors influencing medical charges. The findings can help in understanding the cost drivers in healthcare and potentially inform policy decisions. Future work could involve exploring non-linear models or other advanced techniques to improve prediction accuracy.</span></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>